language: node_js
node_js:
- node
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_f0c3d7f32906_key -iv $encrypted_f0c3d7f32906_iv
  -in .travis/deploy.enc -out .travis/deploy -d
after_success:
- bash misc/deploy.sh
