#!/bin/bash

################################################################################

# Store this file as .git/hooks/commit-msg in your repository in order to

# enforce checking for proper commit message format before actual commits. You

# may need to make the script executable by 'chmod +x .git/hooks/commit-msg'.

################################################################################

filename="$1"

copy=$(tempfile -p gitco)

cat $filename >> $copy

lineno=0



error() {
    echo  "Commit message không hợp lệ !"
    echo  "#Format của commit message:"
    echo  "<Tiêu đề message (60 kí tự)>"
    echo  "<Dòng trống>"
    echo  "<Nội dung message (72 kí tự)>"
    echo  "#Lỗi:"
    echo "$1!"
    echo ""
    exit 1
}



while read -r line
do
    # Ignore comment lines (don't count line number either)
    [[ "$line" =~ ^#.* ]] && continue
    let lineno+=1
    length=${#line}
    # Subject line tests
    if [[ $lineno -eq 1 ]]; then
        [[ $length -gt 60 ]] && error "Tiêu đề chỉ chứa tối đa 60 kí tự"
        [[ ! "$line" =~ ^[A-Z].*$ ]] && error "Kí tự đầu phải viết hoa"
        [[ "$line" == *. ]] && error "Không kết thúc tiêu bằng dấu chấm"
        if [[ ! "$line" =~ ^(Thêm) ]] && [[ ! "$line" =~ ^(Xóa) ]] && [[ ! "$line" =~ ^(Cập nhật) ]] && [[ ! "$line" =~ ^(Sửa lỗi) ]]; then
         error "Phải bắt đầu bằng một trong các từ chỉ định (Thêm/Xóa/Cập nhật/Sửa lỗi)"
     	fi
    fi

    # Rules related to the commit message body
    [[ $lineno -eq 2 ]] && [[ -n $line ]] && error "Tiêu đề với nội dung message phải cách nhau một dòng trống"
    [[ $lineno -gt 1 ]] && [[ $length -gt 72 ]] && error "Nội dung mỗi dòng message chứa tối đa 72 kí tự"

done < "$filename"

rm -f $copy

exit 0